// Run against `npm run dev`: node tests/browser.mjs
import { execFileSync } from 'node:child_process';
import assert from 'node:assert/strict';
const browser = (...args) => execFileSync('npx', ['--yes', 'agent-browser', '--session', 'tempo-check', ...args], { encoding: 'utf8', timeout: 60_000 });
const evaluate = code => browser('eval', code);
const check = code => assert.match(evaluate(`Boolean(${code})`), /true/);
const testUrl = process.env.TEMPO_TEST_URL || 'http://localhost:5173';
browser('open', testUrl);
evaluate('localStorage.clear()');
browser('reload');
check('document.querySelectorAll(".timer-card").length === 3');
check('[...document.querySelectorAll(".timer-card h3")].map(element => element.textContent).join(",") === "딴짓,수학,총 공부시간"');
browser('drag', '.timer-card:nth-child(3) .drag-handle', '.timer-card:nth-child(1)');
check('document.querySelector(".timer-card h3").textContent === "총 공부시간"');
browser('find', 'role', 'button', 'click', '--name', '수학 시작');
browser('find', 'role', 'button', 'click', '--name', '총 공부시간 시작');
check('document.querySelectorAll(".timer-card.running").length === 2');
browser('find', 'role', 'button', 'click', '--name', '수학 1분 추가');
check('JSON.parse(localStorage.getItem("tempo.guest.v1"))[1].runDuration === 1560000');
browser('find', 'role', 'button', 'click', '--name', '수학 설정');
browser('fill', '[name="minutes"]', '10');
browser('find', 'role', 'button', 'click', '--name', '저장하기');
check('JSON.parse(localStorage.getItem("tempo.guest.v1"))[1].duration === 600000 && JSON.parse(localStorage.getItem("tempo.guest.v1"))[1].runDuration === 1560000');
browser('find', 'role', 'button', 'click', '--name', '수학 새로고침');
check('JSON.parse(localStorage.getItem("tempo.guest.v1"))[1].state === "idle" && JSON.parse(localStorage.getItem("tempo.guest.v1"))[1].runDuration === 600000');
browser('find', 'role', 'button', 'click', '--name', '수학 설정');
browser('check', '[name="mode"][value="stopwatch"]');
browser('find', 'role', 'button', 'click', '--name', '저장하기');
check('JSON.parse(localStorage.getItem("tempo.guest.v1"))[1].mode === "stopwatch"');
browser('find', 'role', 'button', 'click', '--name', '수학 설정');
browser('find', 'role', 'button', 'click', '--name', '복제');
check('document.querySelectorAll(".timer-card").length === 4');
browser('find', 'role', 'button', 'click', '--name', '수학 복사 설정');
browser('find', 'role', 'button', 'click', '--name', '맨 앞으로');
check('document.querySelector(".timer-card h3").textContent === "수학 복사"');
browser('reload');
check('document.querySelector(".timer-card h3").textContent === "수학 복사" && document.querySelectorAll(".timer-card").length === 4');
browser('find', 'role', 'button', 'click', '--name', '수학 복사 설정');
browser('find', 'role', 'button', 'click', '--name', '삭제', '--exact');
browser('find', 'role', 'button', 'click', '--name', '삭제하기');
check('document.querySelectorAll(".timer-card").length === 3');
evaluate('window.__sounds = 0; window.AudioContext = class { constructor(){ this.currentTime=0; this.destination={} } resume(){} createOscillator(){ window.__sounds++; return { connect(){}, start(){}, stop(){}, frequency:{ value:0 } } } createGain(){ return { connect(){}, gain:{ setValueAtTime(){}, exponentialRampToValueAtTime(){} } } } }');
browser('find', 'role', 'button', 'click', '--name', '앱 설정');
browser('check', '#sound-toggle');
browser('press', 'Escape');
browser('find', 'role', 'button', 'click', '--name', '타이머 추가', '--exact');
browser('fill', '[name="minutes"]', '0');
browser('fill', '[name="seconds"]', '1');
browser('find', 'role', 'button', 'click', '--name', '만들기');
browser('find', 'role', 'button', 'click', '--name', '타이머1 시작');
browser('wait', '1300');
check('document.querySelector(".timer-card.completed .clock-button").disabled');
evaluate('window.__ringing = window.__sounds');
browser('wait', '2200');
check('window.__sounds > window.__ringing');
browser('find', 'role', 'button', 'click', '--name', '타이머1 새로고침');
check('document.querySelectorAll(".timer-card.completed").length === 0');
evaluate('window.__silence = window.__sounds');
browser('wait', '2200');
check('window.__sounds === window.__silence');
browser('find', 'role', 'button', 'click', '--name', '타이머 추가', '--exact');
browser('check', '[name="mode"][value="stopwatch"]');
browser('find', 'role', 'button', 'click', '--name', '만들기');
check('[...document.querySelectorAll(".timer-card h3")].some(element => element.textContent === "스톱워치1")');
browser('set', 'viewport', '390', '844');
check('document.documentElement.scrollWidth <= 390');
check('document.querySelectorAll(".timer-card")[0].offsetTop === document.querySelectorAll(".timer-card")[1].offsetTop');
browser('screenshot', '/tmp/tempo-mobile.png');
browser('find', 'role', 'button', 'click', '--name', 'Google 로그인');
const tabs = browser('tab', 'list');
assert.ok(tabs.includes(new URL(testUrl).host));
assert.match(tabs, /accounts\.google\.com/);
browser('tab', 'close');
assert.equal(browser('errors').trim(), '');
browser('close');
console.log('Browser checks passed: independent timers, settings, mode switch, reset, clone, ordering, persistence, deletion, completion, mobile layout.');
